let doOrder = document.querySelector('#order');
let fillOutForm = document.querySelector('#fill-out-form');
let cancelOrder = document.querySelector('#cancel');
let massageCancel = document.querySelector('#massageCancel');
let confirmOrder = document.querySelector('#confirm');
let cooking = document.querySelector('#cooking');
let body = document.querySelector('body');
let service = document.querySelector('#service');
let like = document.querySelector('#like');
let dislike = document.querySelector('#dislike');
let checkboxElements = document.querySelectorAll('.checkbox');
let errorMassage = document.querySelector('#alert');
let radioValue = fillOutForm.elements.size.value;
let cheese = document.querySelector('#cheese');
let tomato = document.querySelector('#tomato');
let chicken = document.querySelector('#chicken');
let mushrooms = document.querySelector('#mushrooms');
let sausage = document.querySelector('#sausage');
export{doOrder,cancelOrder,fillOutForm,massageCancel,confirmOrder,cooking,body,service,
    like,dislike,checkboxElements,errorMassage,radioValue,cheese,tomato,chicken,mushrooms,sausage};